male(ali)
male(amjad)
male(khuram)
male(shan)
male(kashif)
male(usman)
male(ahil)
female(samra)
female(sana)
female(naila)
female(nabeela)
female(neha)
female(dania)
female(ayesha)
parent(ali, amjad)
parent(amjad, ahil)
parent(samra, khuram)
parent(khuram, sana)
parent(kashif, samra)
parent(ali, kashif)
parent(naila, ahil)
parent(naila, shan)
parent(samra, sana)
parent(sana, dania)
parent(ayesha, usman
mother(X, Y) :- parent(X, Y), female(Y)
father(X, Y) :- parent(X, Y), male(Y)
brother(X, Y) :- male(X), sibling(X, Y)
sister(X, Y) :- female(X), sibling(X, Y)
grandfather(X, Z) :- parent(X, Y), parent(Y, Z)
grandmother(X, Z) :- female(X), parent(X, Y), parent(Y, Z)
auntuncle(X, Y) :- parent(Z, Y), sibling(X, Z)
husband(X, Y) :- male(X), female(Y), parent(X, Z), parent(Y, Z)
wife(X, Y) :- female(X), male(Y), parent(X, Z), parent(Y, Z)
male(mohi)